FROM node:18-alpine

WORKDIR /app

COPY . .

# yarn ependencies
# RUN yarn add example

RUN yarn install

ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
CMD yarn dev
