FROM node:18-alpine

WORKDIR /app

COPY ./ /app/

WORKDIR /app/api/

VOLUME /app/node_modules
VOLUME /app/api/node_modules

RUN yarn global add @nestjs/cli
#RUN yarn build
RUN yarn install

CMD nest start
