version: '3'

services:
  web:
    container_name: my-read-me-app-dev
    build:
      context: ../../
      dockerfile: Dockerfile

    # # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - ../../.env
    volumes:
      - ../../:/app/
    restart: always
    ports: 
    - "3000:3000"
    networks: 
    - "my-read-me-network-dev"
    depends_on:
    - db
    - redis

  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports: 
    - "5432:5432"

  redis:
    image: "bitnami/redis:7.2.1"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"
    
networks:
  my-read-me-network-dev:
    driver: bridge
    external: true
