version: '3'

services:
  app:
    container_name: my-read-me-app
    build:
      context: .
      dockerfile: Dockerfile

    # # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - ../my-read-me/.env
    volumes:
      - ../my-read-me/:/app/
    restart: always
    ports: 
    - "3000:3000"
    networks: 
    - "my-read-me-network"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports: 
    - "5432:5432"

  redis:
    image: "bitnami/redis:7.2.1"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"
  nginx:
    image: nginx:1.25.2
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/app
    environment:
      - NGINX_HOST=my-read-me.com
      - NGINX_PORT=80

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my-read-me-network:
    driver: bridge
    external: true
