FROM node:18-alpine

WORKDIR /app

COPY . .

# yarn dependencies
# RUN yarn add examples

RUN yarn install
RUN yarn build

ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
CMD yarn start
